name: bayes_nof1
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - pandas
  - numpy
  - matplotlib
  - statsmodels
  - seaborn
  - scikit-learn
  - jupyter
  - flake8
  - python-dotenv>=0.5.1
  - pystan
  - pymc3
